### ISSUE TITLE
Search - identifying scholarship to be considered on topic X

### ISSUE THREAD

**Issue by mdroidian** [samepage-network/samepage.network#127]
# Description

Based on topic `x`, return Authors / Scholars that are 
- most important 
- contrary to consensus position

Based on a particular Author / Scholar, return their
- most recent work

# TODOs

- [x] install flowise
- [x] create "offline" chatflows
  - [x] Topic Generator
  - [x] Authors
  - [x] Most Recent Work
- [ ] create search chatflows
- [ ] create frontend UI prototype

# Resources
## Search
| Provider | Notes | Langchain | Flowise
|--|--|--|--|
| [Perplexity](https://docs.perplexity.ai/) | No selection for "Academic" Focus yet, nor citations |
| [Exa](https://docs.exa.ai/reference/getting-started) | Built in RAG | [✅](https://js.langchain.com/docs/integrations/tools/exa_search) | |
| [Elicit](https://elicit.com/) | No API, but [maybe](https://twitter.com/jungofthewon/status/1560757606007787520)? |
| [Brave](https://brave.com/search/api/) |   |  | [✅](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/tools/BraveSearchAPI) |
| [Tavily](https://tavily.com/#api) |   | [✅](https://js.langchain.com/docs/integrations/tools/tavily_search) |   |
| [SearchApi](https://serpapi.com/) |   |[✅](https://js.langchain.com/docs/integrations/tools/searchapi) | [✅](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/tools/SearchApi) | 
| Google Custom Search |   | [✅](https://python.langchain.com/docs/integrations/tools/google_search) | [✅](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/tools/GoogleSearchAPI) |
